checkoutLocation: "./web-experiments"
workspaceLocation: "."
tasks:
  - name: three-app-launcher
    init: |
        yarn create react-app pwa --template cra-template-pwa-typescript
        cp -r /workspace/web-experiments/copyme/. /workspace/pwa/
        mv /workspace/web-experiments/ /workspace/pwa/src/modules/
        cd /workspace/pwa/
        yarn add react-router-dom @types/react-router-dom
    command: |
      cd /workspace/pwa
      yarn run start
ports:
  - port: 3000
    onOpen: ignore
